trigger:
  branches:
    include:
    - dev
    - release/release-*-MSRC
    exclude:
      - release/dev-*

jobs:
- job:
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: echo "Hello from $(Build.SourceBranch)"
