trigger:
  batch: false
  branches:
    include:
      - dev   
    exclude:
      - dev-*
      - release-*-msrc

schedules:
  - cron: "0 0 * * *"
    displayName: "Daily Midnight build"
    branches:
      include:
      - release-2.0.x-MSRC

jobs:
- job:
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: echo "Hello from $(Build.SourceBranch)"
