trigger:
  batch: false
  branches:
    include:
      - dev   
    exclude:
      - dev-*
      - release-*-msrc

jobs:
- job:
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: echo "Hello from $(Build.SourceBranch)"
