trigger:
  branches:
    include:
    - dev
    - release/release-*-MSRC
    - release/release-1.0.x-MSRC
    exclude:
      - release/dev-*

schedules:
  - cron: "0 0 * * *"
    displayName: "Daily Midnight build"
    branches:
      include:
      - release/release-1.0.x-MSRC

jobs:
- job:
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: echo "Hello from $(Build.SourceBranch)"
